# Generated by Django 5.2.4 on 2025-07-05 12:50

# type: ignore

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme", models.CharField(max_length=100, verbose_name="Тема письма")),
                ("content", models.TextField(verbose_name="Содержание письма")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("fullname", models.CharField(max_length=100, verbose_name="ФИО")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Адресат",
                "verbose_name_plural": "Адресаты",
            },
        ),
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_send_time", models.DateTimeField(null=True, verbose_name="Дата и время первой отправки")),
                ("last_send_time", models.DateTimeField(null=True, verbose_name="Дата и время последней отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("created", "Создана"), ("started", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailwork.message",
                        verbose_name="Содержание сообщения",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="mailwork.recipient", verbose_name="Получатели")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
