# Generated by Django 5.2.5 on 2025-08-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailwork", "0006_alter_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_send_message", "Может отправлять письма"),
                    ("can_view_message", "Может просматривать письма"),
                ],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_finish_newsletter", "Может завершать рассылки"),
                    ("can_view_newsletter", "Может просматривать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_add_recipient", "Может добавлять адресатов"),
                    ("can_view_recipient", "Может просматривать адресатов"),
                ],
                "verbose_name": "Адресат",
                "verbose_name_plural": "Адресаты",
            },
        ),
    ]
